# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: C-DEBI Website Mockup
email: janicak@usc.edu
description: > # this means to ignore newlines until "baseurl:"
  Mockup content re-org for C-DEBI website.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: deepbiosphere
github_username:  cdebi

# Build settings
markdown: kramdown

lsi: false
safe: true
#source: [your repo's top level directory]
incremental: false
highlighter: rouge
gist:
 noscript: false